version: '3.4'
services:
  simpletv-wine:
     container_name: simpletv-wine
     image: achilles85/simpletv-wine:latest
     restart: unless-stopped
     ports:
       - 10000:10000
       - 10002:10002
     network_mode: host
     stdin_open: true
     tty: true