local filter = {

{"bash24","Башкортостан 24 HD"},
{"boxtv","Бокс ТВ"},
{"dom","Домашний"},
{"friday","Пятница!"},
{"fridayp2","Пятница! (+2)"},
{"fridayp4","Пятница! (+4)"},
{"fridayp6","Пятница! (+6)"},
{"kanal5","Пятый канал"},
{"karusel","Карусель"},
{"karuselp2","Карусель (+2)"},
{"karuselp4","Карусель (+4)"},
{"karuselp6","Карусель (+6)"},
{"kinofamily","Киносемья"},
{"kinohit","Кинохит"},
{"kinolove","Киносвидание"},
{"kinoman","Мужское кино"},
{"kinopremier","Кинопремьера"},
{"kultura","Россия К"},
{"m1global","M-1 Global"},
{"matcharena","Матч! Арена"},
{"matcharenahd","Матч! Арена HD"},
{"matchfighter","Матч! Боец"},
{"matchfootball1","Матч! Футбол 1"},
{"matchfootball1hd","Матч! Футбол 1 HD"},
{"matchfootball2","Матч! Футбол 2"},
{"matchfootball2hd","Матч! Футбол 2 HD"},
{"matchfootball3","Матч! Футбол 3"},
{"matchfootball3hd","Матч! Футбол 3 HD"},
{"matchgame","Матч! Игра"},
{"matchgamehd","Матч! Игра HD"},
{"matchoursport","Матч! Страна"},
{"matchpremier","Матч! Премьер"},
{"matchpremierhd","Матч! Премьер HD"},
{"matchtv","Матч!"},
{"matchtvhd","Матч! HD"},
{"mir","Мир"},
{"moscow24","Москва 24"},
{"musicbox","Russian MusicBox"},
{"muztv","Муз ТВ"},
{"ntv","НТВ"},
{"ntvp2","НТВ (+2)"},
{"ntvp4","НТВ (+4)"},
{"ntvp6","НТВ (+6)"},
{"otr","ОТР"},
{"perviy","Первый канал"},
{"perviyhd","Первый канал HD"},
{"perviyp2","Первый канал (+2)"},
{"perviyp4","Первый канал (+4)"},
{"perviyp6","Первый канал (+6)"},
{"probusiness","Про Бизнес"},
{"radost","Радость моя"},
{"ren","Рен ТВ"},
{"renp2","Рен ТВ (+2)"},
{"renp4","Рен ТВ (+4)"},
{"renp6","Рен ТВ (+6)"},
{"rt","Russia Today"},
{"rtdocru","Russia Today Документальный"},
{"russia","Россия 1"},
{"russia24","Россия 24"},
{"russiahd","Россия 1 HD"},
{"russianmb","Russian MusicBox"},
{"russianmbhd","Russian MusicBox HD"},
{"russiap2","Россия 1 (+2)"},
{"russiap4","Россия 1 (+4)"},
{"russiap6","Россия 1 (+6)"},
{"spas","Спас"},
{"sts","СТС"},
{"stsp2","СТС (+2)"},
{"stsp4","СТС (+4)"},
{"stsp6","СТС (+6)"},
{"super","Супер"},
{"t2x2","2x2"},
{"tnt","ТНТ"},
{"tnt4","ТНТ4"},
{"tnthd","ТНТ HD"},
{"tntmusic","ТНТ music"},
{"tntp2","ТНТ (+2)"},
{"tntp4","ТНТ (+4)"},
{"tntp6","ТНТ (+6)"},
{"tochkatv","Точка ТВ"},
{"tv3","ТВ 3"},
{"tv3p2","ТВ 3 (+2)"},
{"tv3p4","ТВ 3 (+4)"},
{"tv3p6","ТВ 3 (+6)"},
{"tvc","ТВЦ"},
{"umortv","Юмор Box"},
{"zvezda","Звезда"},
{"﻿perviy","Первый канал"},

{"unknownplanet","Неизвестная планета"},
{"sovmov","Советское кино"},
{"kinomenu","КиноМеню HD"},
{"rusmult","Советские мультфильмы"},
{"skazki","Сказки зайки"},
{"terra","Terra Incognita"},
{"classickino","Классика кино"},
{"joycook","Joy Cook"},
{"europaplustv","Europa Plus TV"},
{"hdmedia","HD Media"},
{"",""},


}


return filter