--замена названий каналов для остальных плейлистов
DefaultMassNames={
{"5 канал (Россия)", "Пятый Канал"},
{"5 Канал", "Пятый канал"},
{"5 канал", "Пятый канал"},
{"Пятый канал Петербург", "Пятый канал"},
{"Пятый канал Украина", "5 канал (Украина)"},
{"Пятый канал УКР", "5 канал (Украина)"},
{"Пятый канал (Украина)", "5 канал (Украина)"},
{"Ля Минор", "Ля-Минор"},
{"Ля минор", "Ля-Минор"},
{"RBK", "РБК"},
{"РБК ТВ", "РБК"},
{"Телеканал 2x2", "2x2"},
{"ТВ центр", "ТВЦ"},
{"ТВ Центр", "ТВЦ"},
{"ТВЦентр", "ТВЦ"},
{"ТВ3", "ТВ-3"},
{"ТВ 3", "ТВ-3"},
{"TV Centr int.", "ТВ-Центр-Международное"},
{"TVCI", "ТВ-Центр-Международное"},
{"REN ТВ", "Рен ТВ"},
{"REN-TV", "Рен ТВ"},
{"REN TV", "Рен ТВ"},
{"Ren-TV", "Рен ТВ"},
{"РЕНТВ", "Рен ТВ"},
{"РЕН-ТВ", "Рен ТВ"},
{"РенТВ", "Рен ТВ"},
{"РЕН федерал", "Рен ТВ"},
{"Бибигон", "Карусель"},
{"Теленяня", "Карусель"},
{"7 ТВ","Семёрка"},
{"7TV", "Семёрка"},
{"7ТВ", "Семёрка"},
{"7-ТВ", "Семёрка"},
{"MTV rus", "MTV-Russia"},
{"MTV Russia", "MTV-Russia"},
{"МТV Россия", "MTV-Russia"},
{"MTV Россия", "MTV-Russia"},
{"MTV Ukraine", "MTV-Украина"},
{"MTV UKRAINA", "MTV-Украина"},
{"MTV-Dance", "MTV Dance"},
{"MTV-Hits", "MTV Hits"},
{"Sarafan", "Сарафан ТВ"},
{"Cartoon Network/TCM", "Cartoon Network"},
{"CNN News", "CNN"},
{"Discovery Travel&Living", "Discovery Travel & Living"},
{"ТВ-Шансон", "Шансон ТВ"},
{"Шансон_ТВ", "Шансон ТВ"},
{"Детский", "Детский канал"},
{"Детский канал канал", "Детский канал"},
{"Детский канал мир", "Детский мир"},
{"Детский канал Мир/Телеклуб", "Детский Мир"},
{"Детский канал Мир/ТелеКлуб", "Детский Мир"},
{"Universal", "Universal Channel"},
{"Universal Channel channel", "Universal Channel"},
{"Universal Channel Channel", "Universal Channel"},
{"Hallmark", "Diva Universal"},
{"DIVA Universal Channel", "Diva Universal"},
{"Diva Universal Channel", "Diva Universal"},
{"Eurosport Live", "Eurosport"},
{"Eurosport2", "Eurosport 2"},
{"AGRO TV", "Агро ТВ"},
{"Agro TV", "Агро ТВ"},
{"КинопоказHD2", "Кинопоказ HD-2"},
{"КинопоказHD", "Кинопоказ HD-1"},
{"MusicBox RU", "Music Box RU"},
{"Music Box Rus", "Music Box RU"},
{"MusicBox", "Music Box TV"},
{"RTG TV", "Russian Travel Guide"},
{"Техно 24", "24 Техно"},
{"НТВ+", "НТВ-Плюс"},
{"НТВ-Плюс Наше Кино", "Наше Кино"},
{"НТВ-Плюс Спорт 1", "Спорт 1"},
{"Спорт1", "Спорт 1"},
{"SPORT 1", "Спорт 1"},
{"Спорт1 HD", "Спорт 1"},
{"sport 1 HD", "Спорт 1 HD"},
{"Спорт-1", "Спорт 1"},
{"LuxeTV HD", "Luxe TV HD"},
{"НСТ", "Настоящее Страшное ТВ"},
{"Настоящее Страшное ТВ Смешное", "Настоящее Смешное Телевидение"},
{"Смешное ТВ", "Настоящее Смешное Телевидение"},
{"Настоящее Страшное ТВ Страшное", "Настоящее Страшное ТВ"},
{"Настоящее Страшное ТВ Cмешное ТВ", "Настоящее Смешное Телевидение"},
{"BridgeTV", "Bridge TV"},
{"RuTV", "RU.TV"},
{"RUTV", "RU.TV"},
{"RU TV", "RU.TV"},
{"RusongTV", "Rusong TV"},
{"TopShop TV", "Top Shop TV"},
{"Домашний телемагазин", "Домашний магазин"},
{"Mezzo HD", "Mezzo Live HD"},
{"TV5 monde EUROPE", "TV5 Monde"},
{"TV 5 Monde", "TV5 Monde"},
{"HDmedia", "HD Media"},
{"Боец ТВ", "Боец"},
{"Улыбка ребёнка", "Улыбка ребенка"},
{"РТВ", "РазТВ"},
{"TV sale", "TV Sale"},
{"TV club", "TV Club"},
{"Mир", "Мир"},
{"O2TV", "О2ТВ"},
{"O2 TV", "О2ТВ"},
{"БИБИГОН", "Карусель"},
{"RTR-planeta", "РТР Планета"},
{"Az TV", "AzTV"},
{"ТНВ", "Татарстан - Новый Век"},
{"Татарстан - Новый Век - Татарстан", "Татарстан - Новый Век"},
{"Татарстан - Новый Век Татарстан", "Татарстан - Новый Век"},
{"NTV Sport Plus", "Спорт Плюс"},
{"НТВ-Плюс Спортивное ТВ", "Спорт Плюс"},
{"NTV Sport", "НТВ-Плюс Спорт"},
{"NTV Fotbal", "НТВ-Плюс Футбол"},
{"Наш НТВ-Плюс Футбол", "НТВ-Плюс Наш Футбол"},
{"Tennis", "НТВ-Плюс Теннис"},
{"Теннис", "НТВ-Плюс Теннис"},
{"НТВ-Плюс НТВ-Плюс Теннис", "НТВ-Плюс Теннис"},
{"Basketbal Tv", "Баскетбол"},
{"НТВ-Плюс Баскетбол", "Баскетбол"},
{"NTV Fotbal 2", "НТВ-Плюс Футбол 2"},
{"Nas Fotbal", "НТВ-Плюс Наш Футбол"},
{"NAS FUTBOL", "НТВ-Плюс Наш Футбол"},
{"НТВ-Плюс Футбол Украина", "Футбол Украина"},
{"НТВ-Плюс НТВ-Плюс ", "НТВ-Плюс "},
{"Nostalgia Tv", "Ностальгия"},
{"national geografic HD", "National Geographic HD"},
{"wild HD", "Nat Geo Wild HD"},
{"National Geographic Wild", "Nat Geo Wild"},
{"Zvezda Tv", "Звезда"},
{"my zen HD", "MyZen HD"},
{"World", "Discovery World"},
{"Discovery Discovery World", "Discovery World"},
{"Discovery World Fashion", "World Fashion"},
{"BBC Discovery", "BBC"},
{"КХЛ ТВ", "КХЛ-ТВ"},
{"Лучшие хиты", "Кинохит"},
{"Иллюзион+", "Иллюзион +"},
{"TV 1000", "TV1000"},
{"TV1000 action", "TV 1000 Action"},
{"TV1000 Action", "TV 1000 Action"},
{"ACTION TV1000", "TV 1000 Action"},
{"TV1000 Русское Кино", "ТВ-1000 Русское Кино"},
{"TV1000 Русское кино", "ТВ-1000 Русское Кино"},
{"ТВ 1000 русское кино", "ТВ-1000 Русское Кино"},
{"Viasat ТВ1000 Русское кино", "ТВ-1000 Русское Кино"},
{"TV1000 East", "TV1000"},
{"TV1000 EAST", "TV1000"},
{"Премьерный показ", "Премьера"},
{"Клуб ТВ", "Киноклуб"},
{"AXN scifi", "AXN Sci-fi"},
{"AXN Scifi", "AXN Sci-fi"},
{"AXN SciFi", "AXN Sci-fi"},
{"Вести", "Россия 24"},
{"Первый Интерактивный Кавказский", "ПИК"},
{"Jetix", "Disney Channel"},
{"ТТС", "TTC"},
{"sport HD", "HD Спорт"},
{"euroHD Спорт", "Eurosport HD"},
{"EuroHD Спорт", "Eurosport HD"},
{"Style TV", "Style"},
{"НТВ Мир", "НТВ-Мир"},
{"Феникс плюс кино", "Феникс+кино"},
{"Феникс-Кино", "Феникс+кино"},
{"Феникс+ Кино", "Феникс+кино"},
{"Здоровье ТВ", "Здоровое Телевидение"},
{"Zoo Парк", "Зоопарк"},
{"ZooПарк", "Зоопарк"},
{"ZooПАРК", "Зоопарк"},
{"ZOOPARK", "Зоопарк"},
{"Канал Украина", "Украина"},
{"YKRAINA", "Украина"},
{"TRK UKRAINA", "Украина"},
{"TET", "ТЕТ"},
{"HTA", "НТА"},
{"M 1", "М-1"},
{"М1", "М-1"},
{"GAMMA", "Гамма"},
{"NOVLJI KANAL", "Новый канал"},
{"Перший нацiональний", "Первый национальный (Украина)"},
{"PREVLJI NACIONALNI", "Первый национальный (Украина)"},
{"AlYaum", "Al-Yaum"},
{"Tiji TV", "Tiji"},
{"Телеканал Футбол", "Футбол"},
{"Телеканал НТВ-Плюс Футбол", "Футбол"},
{"Футбол Украина", "Футбол (Украина)"},
{"Футбол УКР", "Футбол (Украина)"},
{"НТВ-Плюс Футбол (Украина)", "Футбол (Украина)"},
{"Спорт Онлайн", "Спорт Онлайн"},
{"НТВ-Плюс Спорт Плюс", "Спорт Плюс"},
{"НТВ-Плюс Спорт плюс", "Спорт Плюс"},
{"НТВ-Плюс Футбол НТВ Плюс", "НТВ-Плюс Футбол"},
{"НТВ-Плюс Спорт 2", "Спорт 2"},
{"НТВ-Плюс Спорт 1", "Спорт 1"},
{"Спас", "Спас ТВ"},
{"Спас ТВ ТВ", "Спас ТВ"},
{"XXI век", "TV XXI"},
{"TVXXI", "TV XXI"},
{"KTO-IS-KTO", "Кто есть кто"},
{"Россия 2 (Спорт) (Спорт)", "Россия 2"},
{"Россия 2 (Спорт) (НТВ-Плюс Спорт)", "Россия 2"},
{"ВТВ", "ВТВ (Беларусь)"},
{"ВТВ (Беларусь)_(Беларусь)", "ВТВ (Беларусь)"},
{"ВТВ (Беларусь) (Беларусь)", "ВТВ (Беларусь)"},
{"Индия ТВ", "Индия"},
{"Про деньги", "ProDеньги"},
{"Муз-ТВ", "Муз ТВ"},
{"МузТВ", "Муз ТВ"},
{"Муз_ТВ", "Муз ТВ"},
{"C-Music", "C Music TV"},
{"Bloomberg TV Europe", "Bloomberg"},
{"M1", "M-1"},
{"М2", "M-2"},
{"TBi", "ТВi"},
{"Star TV", "StarTV"},
{"QТВ", "StarTV"},
{"OTV", "O-TV"},
{"News 24", "Новости 24 (Украина)"},
{"ЭкспертТВ", "Эксперт ТВ"},
{"AOne", "A-One"},
{"A ONE", "A-One"},
{"S.E.T.", "SET"},
{"ЮморТВ", "Юмор ТВ"},
{"Jim Jam", "JimJam"},
{"Inter+", "Интер+"},
{"Кино-Non Stop", "Кино Плюс"},
{"Казахстан - CaspioNet", "CaspioNet"},
{"МНОГОсерийное ТВ", "Много ТВ"},
{"Nikelodeon", "Nickelodeon"},
{"TBN Russia", "ТБН"},
{"Viasat_Explorer", "Viasat Explorer"},
{"PERVY KANAL", "Первый канал"},
{"ROSIR 1", "Россия 1"},
{"HTB", "НТВ"},
{"TVC", "ТВЦ"},
{"CTC", "СТС"},
{"THT", "ТНТ"},
{"ТРО Союз", "ТРО"},
{"IHTEP", "Интер"},
{"INTER", "Интер"},
{"Первый Бизнес Канал", "Первый деловой"},
{"Citi","Сiтi"},
{"5 KANAL", "Пятый Канал"},
{"3 KANAL+", "3 канал+"},
{"VREMR", "Вреёя"},
{"DTV", "ДТВ"},
{"ROSSIR 24", "Россия 24"},
{"EURONEWS", "Euronews"},
{"DOMASHIN", "Домашний"},
{"MIR", "Мир"},
{"24 DOK", "24 Док"},
{"ROSSIR KULTURA", "Россия Культура"},
{"TV BULEVAR", "ТВ Бульвар"},
{"365 DNEI", "365 Дней"},
{"MNOGO TV", "Много ТВ"},
{"KTO EST KTO", "Кто есть кто"},
{"INTERESNOE TV", "Интересное ТВ"},
{"SOVRSENO SEKRTNO", "Совершенно Секретно"},
{"SPAS", "Спас ТВ"},
{"INDIR", "Индия"},
{"TATARSTAN", "Татарстан - Новый Век"},
{"7 TV", "7 ТВ"},
{"ZAKON TV", "Закон ТВ"},
{"USADBA", "Усадьба"},
{"ZDROVOE TV", "Здоровое ТВ"},
{"PSIHOLOGIR 21", "Психология 21"},
{"ROSSIR 2", "Россия 2"},
{"NTV PLUS SPORT", "НТВ-ПЛЮС Спорт"},
{"SPORT PLUS", "Спорт ПЛЮС"},
{"НТВ-ПЛЮС Спорт ONLAIN","НТВ-ПЛЮС Спорт Онлайн"},
{"NTV PLUS FUTBOL","НТВ-ПЛЮС Футбол"},
{"NTV PLUS NASH FUTBOL","НТВ-ПЛЮС Наш Футбол"},
{"NTV PLUS FUTBOL 2","НТВ-Плюс Футбол 2"},
{"NTV PLUS TENIS","НТВ-ПЛЮС Теннис"},
{"NTV PLUS BASKETBOL","Баскетбол"},
{"KHL TV","КХЛ-ТВ"},
{"EUROSPORT","Eurosport"},
{"EUROSPORT 2","Eurosport 2"},
{"RUSKY EXTRIM","Русский Экстрим"},
{"EXTREME SPORTS","Extreme Sports"},
{"BOEC","Боец"},
{"PRO POKER","ProPoker"},
{"RU TV","RU.TV"},
{"LR MINOR","Ля-Минор"},
{"MTV RUSSIA","MTV-Russia"},
{"MUZ TV","Муз ТВ"},
{"MEZZO","Mezzo"},
{"MTV ROCKS","MTV Rocks"},
{"VH 1 RUSSIA","VH1-Russia"},
{"VH1 Russia","VH1-Russia"},
{"VH 1 classic","VH1 Classic"},
{"NICKELEDEON","Nickelodeon"},
{"DETSKI Мир","Детский мир"},
{"KARUSEL","Карусель"},
{"CARTOON NETWORK","Cartoon Network"},
{"DISNEY","Disney Channel"},
{"NASHE KINO","Наше кино"},
{"NASHE NOVE KINO","Наше Новое Кино"},
{"KINOHIT","Кинохит"},
{"KINOSOUZ","Киносоюз"},
{"KINOPLUS","Кино ПЛЮС"},
{"KINOCLUB","Киноклуб"},
{"NTV PREMIERA","Премьера"},
{"ZVEZDA","Звезда"},
{"UNIVERSAL","Universal Channel"},
{"SIFY Universal Channel RU","Syfy Universal"},
{"MGM","MGM"},
{"AXN SCY FI","AXN Sci-fi"},
{"KOMEDIR TV","Комедия ТВ"},
{"NOSTALGIA","Ностальгия"},
{"RETRO","Ретро"},
{"DIVA Universal Channel RU","Diva Universal"},
{"FOX CRIME","Fox Crime"},
{"FOX LIFE","Fox Life"},
{"DISCOVERY","Discovery"},
{"ANIMAL PLANET","Animal Planet"},
{"TLC","TLC"},
{"NAT GEO WILD","Nat Geo WILD"},
{"DISCOVERY SCIENCE","Discovery Science"},
{"DISCOVERY WORLD","Discovery World"},
{"NATIONAL GEOGRAPHIC","National Geographic"},
{"National Geografic","National Geographic"},
{"ZONE REALITY","Zone Reality"},
{"DOMASHE ZIVOTNE","Домашние животные"},
{"WORLD FASHION ","World Fashion Channel (рус.)"},
{"MAN TV","MAN TV"},
{"TDK","ТДК"},
{"KUHINA TV","Кухня ТВ"},
{"AVTO PLUS","Авто Плюс"},
{"COMEDY TV","Комеди ТВ"},
{"PARK RAZVLACENHI","Парк развлечений"},
{"OXOTA RIBALKA","Охота и рыбалка"},
{"DRAIV","Драйв"},
{"VOPROS I OVETLJ","Вопросы и ответы"},
{"Первый HD","Первый канал"},
{"НТВ HD","НТВ"},
{"Animаl Planеt HD","Animal Planet HD"}
}
