TVSources_var.Logging		=false
TVSources_var.OSDLang		='Default'
TVSources_var.Default		=''
TVSources_var.FilterName	='%%'
TVSources_var.SourceInFolder =false
TVSources_var.NoSignal		=true
TVSources_var.NextSr		=true
TVSources_var.LastPlay		=false
TVSources_var.CHNameFilter		=true
TVSources_var.LastStart		=0
TVSources_var.AutoBuild		=true
TVSources_var.KeyPlsMake		=false
TVSources_var.AutoBuildFL		=true
TVSources_var.MotherGroup		=true
TVSources_var.AutoBuildDay	={1,0,0,0,0,0,0}
TVSources_var.HotKey		={84,2}
TVSources_var.HotKeyUpd		={78,3}
TVSources_var.HotKeyServ		={0,0}
TVSources_var.DMode			=0
TVSources_var.TimeDelayTweak=0
TVSources_var.ChannelWaiting=20
TVSources_var.RestoreFav	=0
TVSources_var.AutoClearBase	=0
TVSources_var.DelBase		=0
TVSources_var.InfoButton	=1
TVSources_var.ErrRepeatCount=1
TVSources_var.OSDMes		={0,0,1}
TVSources_var.bwDown		=0
TVSources_var.SetGroupOldCh	=1
TVSources_var.SetGroupRegional=0
TVSources_var.UseExtFunc		=0
TVSources_var.ExpandFav		=0
TVSources_var.ServerHttpCache	=7000
TVSources_var.ServerAnswerDelay	=0
TVSources_var.ActiveTab		=5